### ISSUE TITLE
html format is different when it is sent in email

### ISSUE THREAD

**Issue by sachy123** [vernes/YiiMailer#18]
First of all , Thank you for such a fantastic extension! everything is working fine! except when the email format is different than in html/ i mean the css is not applied there.

My code is 
```
$mail = new YiiMailer();
					$mail->setView('contact');
					$mail->setData(
							array(	'message' => $html, 
									'name' => 'John Doe', 
									'description' => 'Contact form'
								));


					$mail->setSmtp('smtp.gmail.com', 465, 'ssl', true, 'abcd@gmail.com', '123sk');

					
					// $mail->setData(array('message' => 'Message to send', 'name' => 'John Doe', 'description' => 'Contact form'));

					if ($mail->send()) {
					    echo "Thank you for contacting us. We will respond to you as soon as possible";
					} else {
					     echo "Error while sending email: ".$mail->getError();
					}
					exit();
```

So I try to echo the $html contents and I get this >>>>>>>>>

![screen shot 2014-11-13 at 7 33 29 pm](https://cloud.githubusercontent.com/assets/6980311/5035569/92e8063c-6b78-11e4-9b5d-8beb496cf4ec.png)

And when I receive the email the format is as below >>>>>
![screen shot 2014-11-13 at 7 33 50 pm](https://cloud.githubusercontent.com/assets/6980311/5035561/7643fcac-6b78-11e4-92d0-334109578575.png)

**Comment by vernes** [comment]
Be sure to include full html layout with css and everything. Check your layout file and view file.
