### ISSUE TITLE
Sending mail returns boolean true but no mail is sent.

### ISSUE THREAD

**Issue by pimduijst** [vernes/YiiMailer#25]
Hi,

This is I know a kind of global question but I don't know where to start. I compose a mail according to the docs and call $mail->send() which returns the value 1 as in true.

Unfortunatly a mail is not sent, also it did not came in my spam-folder. How can I debug this?

Kind regards,

Pim

**Comment by pimduijst** [comment]
*ahum the title was wrong, changed it to a correct more describing title*

**Comment by vernes** [comment]
Hi

send() returns true or false, not integer. Are you sure you are not getting some other error? Did you try testMode? Are you using SMTP or not? Some code sample maybe?

**Comment by pimduijst** [comment]
Oke... this is almost embarrassing haha, I did got mails like it should. Everything went well, I only forgot that in my gmail-account I got a filter that archived them to another folder instead of my main-inbox hahaha
