### ISSUE TITLE
YiiMailer 2.x with composer support and updated PHPMailer 6.x

### ISSUE THREAD

**Issue by bkonetzny** [vernes/YiiMailer#33]
We are using YiiMailer 1.6 in our project and I want to say thanks for this great extension.
Currently, we are looking in to updating the PHPMailer to 6.x as there are some improvements in DKIM we want to see in our code.
Is an update to PHPMailer 6.x planned for this extension?
We are willing to fork this project and contribute a PR to make a "version 2" of this extension which is composer compatible and installs PHPMailer 6.x as a dependency - is this something you would accept as a PR if we would work on this, or is this extension in maintenance only? :)

**Comment by vernes** [comment]
It's good to hear you found it useful. 

As for PHPMailer 6, I haven't really looked into breaking changes and further development in that regard. This extension is in maintenance but I would gladly accept any PR. There is for some time separate 'composer' branch https://github.com/vernes/YiiMailer/tree/composer

Maybe i'ts time to push it to master as well, so "version 2" you are talking about makes a lot of sense. 
Thanks

**Comment by bkonetzny** [comment]
Ok, to not break stuff with the 1.x version, should I fork the composer branch and update the PHPMailer there, and then create a PR based on this branch?
This way the 2.x release could be composer based and contain the latest PHPMailer.
What do you think?

**Comment by vernes** [comment]
Yes, that sounds good.

**Comment by bkonetzny** [comment]
Thanks for merging the PR, now it's at least possible to install as a dev release directly from this git branch.
What about releasing an official release on packagist? In the PR I continued to use the `rdewilde/yiimailer` naming you had in the composer branch, but that seems to be a different user, so it might need an update (to `vernes/yiimailer` I guess) if you publish this on your behalf?
What are your plans about this? :)

**Comment by vernes** [comment]
Thank you for the PR :)

Yes, I will merge this branch to master and publish to packagist as soon as possible.

**Comment by bkonetzny** [comment]
I see a 2.x package is now published to https://packagist.org/packages/vernes/yiimailer - but it seems to have errors. Readme still names the old package and PHPMailer dependency is set to 5.x - seems packagist has used an outdated master for this release? Can you check this and republish?

**Comment by vernes** [comment]
Thanks, I didn't check it properly, packagist was using old tag 2.0 as "latest" stable release, dev-master was ok. I tagged and released v3.0 now and it seems ok.

**Comment by bkonetzny** [comment]
Thanks, that did work! :)
Closing this issue now :)

**Comment by vernes** [comment]
Thank you for all the work!
