### ISSUE TITLE
No change from 3.0 to 4.0 when updating with composer

### ISSUE THREAD

**Issue by bkonetzny** [vernes/YiiMailer#37]
Running `composer outdated` gives update from 3.0 to 4.0:
```
$ composer outdated
vernes/yiimailer    v3.0    v4.0    Yii extension for sending emai...
```

But running `composer update vernes/yiimailer` will do nothing:
```
$ composer update vernes/yiimailer
Loading composer repositories with package infoUpdating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
```

Is the package correctly published to packagist?

**Comment by vernes** [comment]
Sorry for a late response. Version 4.0 changed autoloading and paths and it required major version change:
https://github.com/vernes/YiiMailer/pull/36

**Comment by bkonetzny** [comment]
Ah, sorry, my version contraint was ^3.0, so update didn't work. Thanks for clarification!
